fix: Prevent ArrayIndexOutOfBoundsException in StartOnBoard pass-through.
This commit log the cause of the exception. We do this to prevent the search from failing
and to gather more information about the error. There seems to be something wrong in the
timetable data - the trip is boarded in the last segment, so why is it not possible
to board the same trip in the same stop?

java.lang.ArrayIndexOutOfBoundsException: Index -4 out of bounds for length 78
  at o.o.routing.algorithm.raptoradapter.transit.request.TripPatternForDates.departureTime(TripPatternForDates.java:213)
  at o.o.routing.algorithm.raptoradapter.transit.request.TripScheduleWithOffset.departure(TripScheduleWithOffset.java:50)
  at o.o.raptor.rangeraptor.multicriteria.MultiCriteriaRoutingStrategy.boardWithStartOnBoardAccess(MultiCriteriaRoutingStrategy.java:129)